config/routes.rb
Earthquakes::Application.routes.draw do
  root :to => 'earthquakes#index'
  match '/earthquakes/search' => 'earthquakes#search'
  resources :earthquakes

end

app/models/earthquake.rb
# == Schema Information
#
# Table name: earthquakes
#
#  id         :integer          not null, primary key
#  place      :string(255)
#  latitude   :float
#  longitude  :float
#  magnitude  :float
#  time       :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Earthquake < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :magnitude, :place, :time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter  :set_baseurl
  helper :application

  def set_baseurl
    @baseurl = "http://comcat.cr.usgs.gov/fdsnws/event/1/query?format=geojson&orderby=time&maxlatitude=70&minlatitude=5&maxlongitude=-70&minlongitude=-161&minmagnitude=3&"
  end
  
  # http://comcat.cr.usgs.gov/fdsnws/event/1/query?starttime=2014-03-24%2000:00:00&maxlatitude=70&minlatitude=5&maxlongitude=-70&minlongitude=-161&minmagnitude=3&format=geojson&endtime=2014-03-31%2023:59:59&orderby=time
  
end

app/controllers/earthquakes_controller.rb
class EarthquakesController < ApplicationController
  layout 'superhero'
  require 'rest_client'
  require 'open-uri'
  
  # GET /earthquakes
  # GET /earthquakes.json
  def index
    # http://comcat.cr.usgs.gov/fdsnws/event/1/query?starttime=2014-03-23%2000:00:00&minmagnitude=2&format=geojson&endtime=2014-03-30%2023:59:59&orderby=time
    starttime = '2014-03-30%2000:00:00'
    endtime = '2014-03-30%2023:59:59'
    minmag = '2'
    url  = @baseurl + "starttime="+ starttime +"&minmagnitude=" + minmag + "&endtime=" + endtime
    search_url = URI::encode(url)
    logger.info "#{url}"
    @earthquakes = RestClient.get url, :accept => :json
 #  @earthquakes = JSON.parse(@earthquakes, {:symbolize_names => true})
 #  
 #  @geojson = Array.new
 #  
 #  @earthquakes[:features].each do |earthquake|
 #    @geojson <<{
 #      type: 'Feature',
 #      geometry: {
 #        type: 'Point',
 #        coordinates: earthquake[:geometry][:coordinates]
 #      },
 #      properties: {
 #        place: earthquake[:properties][:place],
 #        time: earthquake[:properties][:time],
 #        mag: earthquake[:properties][:mag]
 #      }
 #    }
 #  end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @earthquakes }
    end
  end
  
  # GET /earthquakes/search
  # GET /earthquakes/search.json
  def search
    @starttime = params[:start]
    @endtime = params[:end]
    @minmag = params[:mag]
    url  = @baseurl + "starttime="+ @starttime +"&minmagnitude=" + @minmag + "&endtime=" + @endtime
    search_url = URI::encode(url)
    logger.info "----------------#{search_url}"
    @result = RestClient.get search_url, :accept => :json
    
    respond_to  do |format|
      format.html
      format.json { render json: @result }
      format.js
    end    
  end
  

  # GET /earthquakes/1
  # GET /earthquakes/1.json
  def show
    @earthquake = Earthquake.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @earthquake }
    end
  end

  # GET /earthquakes/new
  # GET /earthquakes/new.json
  def new
    @earthquake = Earthquake.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @earthquake }
    end
  end

  # GET /earthquakes/1/edit
  def edit
    @earthquake = Earthquake.find(params[:id])
  end

  # POST /earthquakes
  # POST /earthquakes.json
  def create
    @earthquake = Earthquake.new(params[:earthquake])

    respond_to do |format|
      if @earthquake.save
        format.html { redirect_to @earthquake, notice: 'Earthquake was successfully created.' }
        format.json { render json: @earthquake, status: :created, location: @earthquake }
      else
        format.html { render action: "new" }
        format.json { render json: @earthquake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /earthquakes/1
  # PUT /earthquakes/1.json
  def update
    @earthquake = Earthquake.find(params[:id])

    respond_to do |format|
      if @earthquake.update_attributes(params[:earthquake])
        format.html { redirect_to @earthquake, notice: 'Earthquake was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @earthquake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /earthquakes/1
  # DELETE /earthquakes/1.json
  def destroy
    @earthquake = Earthquake.find(params[:id])
    @earthquake.destroy

    respond_to do |format|
      format.html { redirect_to earthquakes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/earthquakes_helper.rb
module EarthquakesHelper
end

app/views/earthquakes/_form.html.erb
<%= form_for @earthquake, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :place, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :place, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :magnitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :magnitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :time, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                earthquakes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/earthquakes/_search.html.erb
              <%= form_tag "/earthquakes/search", :remote => true, :method => :get, :id => 'search', :authenticity_token => false, :class => 'form-search'  do %>
                  <%= text_field_tag :start, nil, "data-format" => "yyyy-MM-dd HH:mm:ss", :placeholder => "start", :class => 'input-medium' %>
				  <%= text_field_tag :end, nil, "data-format" => "yyyy-MM-dd HH:mm:ss", :placeholder => "end", :class => 'input-medium' %>
				  <%= text_field_tag :mag, nil,  :placeholder => "mag", :class => 'input-small' %>
                  <%= button_to "Search" , earthquakes_search_path, :class => 'btn btn-primary' %>
              <% end %>

app/views/earthquakes/edit.html.erb
<%- model_class = Earthquake -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/earthquakes/new.html.erb
<%- model_class = Earthquake -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/earthquakes/search.html.erb
<% content_for(:side_bar) do %>
    <%= render :partial => "search" %>
<% end %>

app/views/earthquakes/search.js.erb
console.log("before search.js.erb")



var url = "/earthquakes/search.json?start=" + "<%= URI.encode(@starttime) %>" + "&end=" + "<%=  URI.encode(@endtime) %>" + "&mag=" + "<%=  URI.encode(@minmag) %>";

console.log(url);
$('#map').clear;
//map = L.mapbox.map('map', 'sudhakarsjce.hlfg5pke');


var featureLayer = L.mapbox.featureLayer()
    .loadURL(url)
    .addTo(map);

	featureLayer.on('ready', function() {
	    // featureLayer.getBounds() returns the corners of the furthest-out markers,
	    // and map.fitBounds() makes sure that the map contains these.
	    map.fitBounds(featureLayer.getBounds());
	});
	
	console.log("after search.js.erb")

app/views/earthquakes/show.html.erb
<%- model_class = Earthquake -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
  <dd><%= @earthquake.place %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @earthquake.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @earthquake.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:magnitude) %>:</strong></dt>
  <dd><%= @earthquake.magnitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time) %>:</strong></dt>
  <dd><%= @earthquake.time %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              earthquakes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_earthquake_path(@earthquake), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              earthquake_path(@earthquake),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Earthquakes" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
	<%= stylesheet_link_tag "bootstrap_theme", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Earthquakes</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/superhero.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "earthquakes" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
   <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css' rel='stylesheet' />
   <style>
     body { margin:0; padding:0; }
     #map { position:absolute; top:0; bottom:0; width:74%; }
   </style>
   
 
   
    <%= stylesheet_link_tag "superhero", :media => "all" %>
 	<%= stylesheet_link_tag "bootstrap-datetimepicker"	, :media => "all" %> 

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
	
	
  </head>
  <body>

<div class="container-fluid">
	<div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="#">Earthquakes</a>
	   
	  </div>
	</div>
	
   <div class="row-fluid">
    <div class="span4">
      <!--Sidebar content-->
      <div class="well sidebar-nav">

		  <h4>Search</h4>
		  <%= render :partial => 'search' %>
		  
      </div><!--/.well -->
    </div>
    <div class="span8">
 	   
   	 <div id="map">
	  <%= bootstrap_flash %>
	  
	  <%= yield %>
	  
    </div>
  </div>
</div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "superhero" %>
	 <%= javascript_include_tag "bootstrap-datetimepicker" %>
 
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>